### ISSUE TITLE
Unable to keep initial connection open

### ISSUE THREAD

**Issue by kernelkraut** [gitibeyonde/openevse-ocpp#1]
I'm unable to keep the initial connection open by running ocpp.py. I can execute and the websocket appears to connect but it looks like the second request is returning "Connection is already closed"

pi@ocppclient:/opt/evdevice/ocpp $ --- request header ---
DEBUG:websocket:--- request header ---
GET /steve/websocket/CentralSystemService/322d2db2 HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: ***RemovedServerName***:8443
Origin: http://***RemovedServerName***:8443
Sec-WebSocket-Key: Ke1LqPp6JvwJfbJ22U8Dow==
Sec-WebSocket-Version: 13
Sec-WebSocket-Protocol: ocpp1.5

DEBUG:websocket:GET /steve/websocket/CentralSystemService/322d2db2 HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: ***RemovedServerName***:8443
Origin: http://***RemovedServerName***:8443
Sec-WebSocket-Key: Ke1LqPp6JvwJfbJ22U8Dow==
Sec-WebSocket-Version: 13
Sec-WebSocket-Protocol: ocpp1.5

-----------------------
DEBUG:websocket:-----------------------
--- response header ---
DEBUG:websocket:--- response header ---
INFO:root:on_error: Error received Connection is already closed.
INFO:root:on_close: ### closed_**

**Comment by kernelkraut** [comment]
Ok figured out the issue - We are using 8443 on https (with a certificate). I had to change the ocpp.py: (Had to change ws to wss @  ws = websocket.WebSocketApp under the main method)
    
    try:
        uuid = utils.getUuid()
        conf = datastore.Datastore()
        client_cmd = client_call.ClientCall(conf)
        registry = request_registry.RequestRegistry()
            
        websocket.enableTrace(True)
        ws = websocket.WebSocketApp("wss://" + SIP + "/steve/websocket/CentralSystemService/" + uuid,
                                    on_message=on_message,
                                    on_error=on_error,
                                    on_close=on_close,
                                    header=[ "Sec-WebSocket-Protocol: ocpp1.5"])


![image](https://user-images.githubusercontent.com/23164186/62599797-76b76080-b8ed-11e9-9ae5-9ade2df76515.png)

**Comment by gitibeyonde** [comment]
If this can be made configurable, even better.

**Comment by kernelkraut** [comment]
#2

**Comment by kernelkraut** [comment]
> If this can be made configurable, even better.
> […](#)

I've added some new pull requests for a new SSL variable and added you for review. 

![image](https://user-images.githubusercontent.com/23164186/62696362-8b245780-b9d8-11e9-8748-5a6c32f3d2c9.png)

**Comment by kernelkraut** [comment]
Closing off issue - Added SSL variable in system.properties.
